categories = [
    {"id": 1, "group": "Dama", "name": "Pulsera"},
    {"id": 2, "group": "Dama", "name": "Collar"},
    {"id": 3, "group": "Dama", "name": "Aretes"},
    {"id": 4, "group": "Dama", "name": "Tobillera"},
    {"id": 5, "group": "Dama", "name": "Anillo"},
    /*{"id": 6, "group": "Dama", "name": "Dije"},*/
    {"id": 7, "group": "Caballero", "name": "Pulsera"},
    {"id": 8, "group": "Infantil", "name": "Pulsera"},
    {"id": 9, "group": "Cajas de regalo", "name": "CAJAS DE REGALO"},
    {"id": 10, "group": "Joyas para compartir", "name": "JOYAS PARA COMPARTIR"}
]

catalog = [   

    {"id": "001", 
    "title": "SET DE PULSERAS CON ORO DE 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO DE 18 KT 001",
    "category": 1, 
    "price" : "$53.000", 
    "image": ["001-01.jpg", "001-02.jpg", "001-03.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b> <br>Mostacilla japonesa.<br>Hilo encerado.<br>Un (1) balin de oro 18 quilates tamaño  N°3mm."},
   
    {"id": "002", 
    "title": "PULSERA CON ORO 18 KT", 
    "keywords": "PULSERA CON ORO 18 KT 002",
    "category": 1, 
    "price" : "$40.000", 
    "image": ["002-01.png", "002-02.jpg", "002-03.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca.<br><br><b>Materiales:</b><br>Hilos con brillo.<br>Hilo encerado.<br>Un(1) balin de oro 18 quilates tamaño N3mm."}, 

    {"id": "003", 
    "title": "SET DE PULSERAS CON ORO DE 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO DE 18 KT 003",
    "category": 1, 
    "price" : "$82.000", 
    "image": ["003-01.jpg", "003-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N°4mm."}, 

    {"id": "004", 
    "title": "SET DE PULSERAS CON ORO DE 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO DE 18 KT 004",
    "category": 1, 
    "price" : "$65.000", 
    "image": ["004-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N°3mm."}, 

    {"id": "005", 
    "title": "PULSERA CON ORO 18 KT", 
    "keywords": "PULSERA CON ORO 18 KT 005",
    "category": 1, 
    "price" : "$52.000", 
    "image": ["005-01.png", "005-02.png"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N°4mm."}, 

    {"id": "006", 
    "title": "SET DE PULSERAS CON ORO DE 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO DE 18 KT 006",
    "category": 1, 
    "price" : "$110.000", 
    "image": ["006-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Tres (3) balines de oro 18 quilates tamaño N°3mm."}, 

    {"id": "007", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS DIJE CRUZ 007",
    "category": 1, 
    "price" : "$38.000", 
    "image": ["007-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "008", 
    "title": "PULSERA MANO JAMSA", 
    "keywords": "PULSERA DIJE MANO JAMSA OJO 008",
    "category": 1, 
    "price" : "$35.000", 
    "image": ["008-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo coreano."}, 
    
    {"id": "009", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT CORAZON PEYOTE 5 BALINES 009",
    "category": 1, 
    "price" : "$218.000", 
    "image": ["009-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa. <br>Hilos con brillo. <br>Hilo encerado. <br>Siete (7) balines de oro 18 quilates tamaño N3mm.*"}, 

    {"id": "010", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS DIJE CRUZ SAGRADO CORAZON 010",
    "category": 1, 
    "price" : "$43.000", 
    "image": ["010-01.jpg", "010-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "011", 
    "title": "TOBILLERA CON ORO 18 KT", 
    "keywords": "TOBILLERA CON ORO 18 KT MARIPOSA FUCSIA AZUL 011",
    "category": 4, 
    "price" : "$115.000", 
    "image": ["011-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu tobillo. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo coreano. <br>Cuatro (4) balines de oro 18 quilates tamaño N3mm."}, 

    {"id": "012", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT CORAZON 012",
    "category": 1, 
    "price" : "$81.000", 
    "image": ["012-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N4mm."}, 

    {"id": "013", 
    "title": "SET DE PULSERAS CON ORO 18 KT",
    "keywords": "SET DE PULSERAS CON ORO 18 KT 013", 
    "category": 1, 
    "price" : "$279.000", 
    "image": ["013-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Siete (7) balines de oro 18 quilates tamaño N4mm."}, 

    {"id": "014", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT CORAZON 014",
    "category": 1, 
    "price" : "$98.000", 
    "image": ["014-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Hilos con brillo. <br>Dos (2) balines de oro 18 quilates tamaño N3mm."}, 

    {"id": "015", 
    "title": "PULSERA CON ORO 18 KT", 
    "keywords": "PULSERA COLORIDA CON ORO 18 KT COLORINCHE 015",
    "category": 1, 
    "price" : "$80.000", 
    "image": ["015-01.jpg", "015-02.png"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo coreano.<br>Tres (3) balines de oro 18 quilates tamaño N3mm."}, 

    {"id": "016", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT 016",
    "category": 1, 
    "price" : "$93.000", 
    "image": ["016-01.jpg", "016-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Tres (3) balines de oro 18 quilates tamaño N3mm."}, 

    {"id": "017", 
    "title": "PULSERA CON ORO 18 KT", 
    "keywords": "PULSERA CON ORO 18 KT TEJIDO HILO ENCERADO ROJO 017",
    "category": 1, 
    "price" : "$80.000", 
    "image": ["017-01.jpg", "017-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Hilo encerado. <br>Tres (3) balines de oro 18 quilates tamaño N3mm."}, 

    {"id": "018", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT 018",
    "category": 1, 
    "price" : "$83.000", 
    "image": ["018-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N4mm."}, 

    {"id": "019", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS PEYOTE COLORES VIBRANTES NARANJA 019",
    "category": 1, 
    "price" : "$45.000", 
    "image": ["019-01.jpg", "019-02.jpg", "019-03.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "020", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS PEYOTE ROJO TILA ROJA 020",
    "category": 1, 
    "price" : "$40.000", 
    "image": ["020-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "021", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS 021",
    "category": 1, 
    "price" : "$36.000", 
    "image": ["021-01.jpg", "021-02.jpg", "021-03.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "022", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS MORADO LILA CORAZON 022",
    "category": 1, 
    "price" : "$41.000", 
    "image": ["022-01.jpg", "022-02.jpg", "022-03.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "023", 
    "title": "PULSERA CORAZÓN", 
    "keywords": "PULSERA CORAZÓN OSCURA LILA MORADO 023",
    "category": 1, 
    "price" : "$25.000", 
    "image": ["023-01.jpg", "023-02.jpg", "023-03.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "024", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS PERLA ENFILADA PEYOTE 024",
    "category": 1, 
    "price" : "$45.000", 
    "image": ["024-01.jpg", "024-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Perla natural."}, 

    {"id": "025", 
    "title": "PULSERA", 
    "keywords": "PULSERA DROPS LAGRIMAS PEYOTE 025",
    "category": 1, 
    "price" : "$35.000", 
    "image": ["025-01.jpg", "025-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "026", 
    "title": "PULSERA CORAZONES", 
    "keywords": "PULSERA CORAZONES TRES 3 026",
    "category": 1, 
    "price" : "$26.000", 
    "image": ["026-01.jpg", "026-02.jpg", "026-03.jpg", "026-04.jpg", "026-05.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "027", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS SWAROSKI TILA LILA ENFILADA 027",
    "category": 1, 
    "price" : "$48.000", 
    "image": ["027-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Aplique de cristal de Swaroski."}, 

    {"id": "028", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS TELAR NUDE 028",
    "category": 1, 
    "price" : "$61.000", 
    "image": ["028-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "029", 
    "title": "PULSERAS", 
    "keywords": "PULSERA COLORIDA COLORINCHE 1 FILA 029",
    "category": 1, 
    "price" : "$15.000", 
    "image": ["029-01.jpg", "029-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "030", 
    "title": "SET DE CADENA Y ARETES MASCOTA", 
     "keywords": "SET DE CADENA Y ARETES MASCOTA DIJE GATO 030",
    "category": 2, 
    "price" : "$53.000", 
    "image": ["030-01.jpg", "030-02.jpg", "030-03.jpg", "030-04.jpg", "030-05.jpg"],
    "description": "Elaboramos los rostros de mascotas que el cliente solicite. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado.<br>Cadena de acero dorado medida aproximada 40cm de largo. (Los tejidos varian según disponibilidad)."}, 
    
    {"id": "031", 
    "title": "ARETES TOPOS GEOMÉTRICOS", 
    "keywords": "ARETES TOPOS GEOMÉTRICOS DORADO OSCURO BLANCO 031",
    "category": 3, 
    "price" : "$55.000", 
    "image": ["031-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "032", 
    "title": "PULSERA CON INICIAL",
    "keywords": "PULSERA CON INICIAL LETRA DIJE 032",
    "category": 1, 
    "price" : "$20.000", 
    "image": ["032-01.jpg", "032-02.jpg", "032-03.jpg", "032-04.jpg", "032-05.jpg", "032-06.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "033", 
    "title": "PULSERA MASCOTA", 
    "keywords": "PULSERA MASCOTA DIJE PERRO DIJE PERRITO 033",
    "category": 1, 
    "price" : "$30.000", 
    "image": ["033-01.jpg", "033-02.jpg", "033-03.jpg", "033-04.jpg", "033-05.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Se personaliza la carita de la mascota. <br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "034", 
    "title": "ANILLO", 
    "keywords": "ANILLO 034",
    "category": 5, 
    "price" : "$30.000", 
    "image": ["034-01.jpg"],
    "description": "Se realiza a la medida del cliente.<br><br><b>Materiales:</b><br>Mostacilla japonesa."}, 
    
    {"id": "035", 
    "title": "MAXIARETES", 
    "keywords": "ARETES MAXIARETES VERDE DORADO 035",
    "category": 3, 
    "price" : "$60.000", 
    "image": ["035-01.jpg", "035-02.jpg", "035-03.jpg", "035-04.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 
      
    {"id": "036", 
    "title": "MAXIARETES", 
    "keywords": "ARETES MAXIARETES COLORES 036",
    "category": 3, 
    "price" : "$80.000", 
    "image": ["036-01.jpg", "036-02.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 
     
    {"id": "037", 
    "title": "MAXIARETES DESDE LA MONTAÑA", 
    "keywords": "MAXIARETES DESDE LA MONTAÑA ARETES VERDE 037",
    "category": 3, 
    "price" : "$80.000", 
    "image": ["037-01.jpg"],
    "description": "Inspirados en la experiencia de viaje hacia  la Reserva Forestal de de Coraza, Chalan-Sucre.<br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "038", 
    "title": "SET DE ANILLOS", 
    "keywords": "SET DE ANILLOS ANILLO DELGADO 038",
    "category": 5, 
    "price" : "$38.000", 
    "image": ["038-01.jpg"],
    "description": "Se realiza a la medida del cliente. <br><br><b>Materiales:</b><br>Mostacilla japonesa."}, 

    {"id": "039", 
    "title": "ANILLO", 
    "keywords": "ANILLO GRANDE NEGRO ROJO 039",
    "category": 5, 
    "price" : "$45.000", 
    "image": ["039-01.jpg"],
    "description": "Se realiza a la medida del cliente. <br><br><b>Materiales:</b><br>Mostacilla japonesa."}, 

    {"id": "040", 
    "title": "PULSERA", 
    "keywords": "PULSERA PEYOTE ROMBOS HOMBRE CABALLERO 040",
    "category": 7, 
    "price" : "$32.000", 
    "image": ["040-01.jpg", "040-02.jpg", "040-03.jpg", "040-04.jpg", "040-05.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "041", 
    "title": "MAXIARETES VERANERAS", 
    "keywords": "MAXIARETES VERANERAS ARETES FLOR FUCSIA FLORES 041",
    "category": 3, 
    "price" : "$110.000", 
    "image": ["041-01.jpg", "041-02.jpg"],
    "description": "Inspirados en la veranera que con su majestuoso color fucsia, embellece nuestras casas y paisajes de la región.<br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "042", 
    "title": "PULSERA", 
    "keywords": "PULSERA NOMBRE TELAR 042",
    "category": 1, 
    "price" : "$25.000", 
    "image": ["042-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "043", 
    "title": "PULSERA MARIPOSA", 
    "keywords": "PULSERA MARIPOSA 043",
    "category": 1, 
    "price" : "$30.000", 
    "image": ["043-01.jpg", "043-02.jpg"], 
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo coreano."}, 

    {"id": "044", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS PASTEL TILA 044",
    "category": 1, 
    "price" : "$38.000", 
    "image": ["044-01.jpg", "044-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado.<br>"}, 

    {"id": "045", 
    "title": "MAXIARETES", 
    "keywords": "ARETES MAXIARETES FLOR DORADO AZUL MORADO LILA 045",
    "category": 3, 
    "price" : "$80.000", 
    "image": ["045-01.jpg", "045-02.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    /*
    {"id": "046", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT ZIGZAG PEYOTE",
    "category": 1, 
    "price" : "$160.000", 
    "image": ["046-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Cinco (5) balines de oro 18 quilates tamaño N3mm."}, 
    */

    {"id": "047", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT TONOS TIERRA 047",
    "category": 1, 
    "price" : "$63.000", 
    "image": ["047-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N3mm."}, 

    {"id": "048", 
    "title": "PULSERA CON ORO 18 KT", 
    "keywords": "PULSERA CON ORO 18 KT 2 CORAZONES BALIN DELGADA ANCHA 048",
    "category": 1, 
    "price" : "$49.000", 
    "image": ["048-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N3mm."}, 

    {"id": "049", 
    "title": "SET DE PULSERAS CORAZÓN", 
    "keywords": "SET DE PULSERAS CORAZONES DE COLORES CORAZON 049",
    "category": 1, 
    "price" : "$64.000", 
    "image": ["049-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Hilo coreano."}, 

    {"id": "050", 
    "title": "ANILLO", 
    "keywords": "ANILLO NEGRO ROMBO 050",
    "category": 5, 
    "price" : "$35.000", 
    "image": ["050-01.jpg", "050-02.jpg"],
    "description": "Se realiza a la medida del cliente. <br><br><b>Materiales:</b><br>Mostacilla japonesa."}, 

    {"id": "051", 
    "title": "PULSERA", 
    "keywords": "PULSERA CORAZON CORAZONES DE COLORES 051",
    "category": 1, 
    "price" : "$40.000", 
    "image": ["051-01.jpg", "051-02.jpg", "051-03.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo coreano."}, 

    {"id": "052", 
    "title": "ANILLO", 
    "keywords": "ANILLO 052",
    "category": 5, 
    "price" : "$25.000", 
    "image": ["052-01.jpg", "052-02.jpg", "052-03.jpg", "052-04.jpg"],
    "description": "Se realiza a la medida del cliente. <br><br><b>Materiales:</b><br>Mostacilla japonesa."}, 

    /*
    {"id": "053", 
    "title": "PULSERA RELIGIOSA", 
    "keywords": "PULSERA RELIGIOSA DIJE VIRGEN GUADALUPE GUADALUPANA",
    "category": 1, 
    "price" : "$40.000", 
    "image": ["053-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo."}, 
    */
    
    {"id": "054", 
    "title": "COLLAR CHOKER CRUZ", 
    "keywords": "COLLAR CHOKER ESCAPULARIO CRUZ DIJE 054",
    "category": 2, 
    "price" : "$40.000", 
    "image": ["054-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Sistema de cierre con herrajes de acero dorado. <br>Medida aproximada del collar entre 36 a 38 cm."}, 

    {"id": "055", 
    "title": "CADENA CON DIJE ADVOCACIÓN VIRGEN", 
    "keywords": " SET CADENA CON DIJE RELIGIOSO VIRGEN VIRGENES ADVOCACIONES 055",
    "category": 2, 
    "price" : "$32.000", 
    "image": ["055-01.jpg"],
    "description": "Se elaboran las advocaciones de la Virgen.<br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Cadena de acero dorado, medida aproximada de 40cm. (Los tejidos varian según disponibilidad)."}, 

    {"id": "056", 
    "title": "SET DE PULSERAS CON ORO 18KT", 
    "keywords": "SET DE PULSERAS CON ORO 18KT BALIN ORO caballero 056",
    "category": 7, 
    "price" : "$65.000", 
    "image": ["056-01.jpg", "056-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N4mm."}, 

    {"id": "057", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT 3 balines caballero 057",
    "category": 7, 
    "price" : "$98.000", 
    "image": ["057-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado.<br>Tres (3) balines de oro 18 quilates tamaño N3mm."}, 

    {"id": "058", 
    "title": "ARETES TOPOS GEOMÉTRICOS", 
    "keywords": "ARETES TOPOS GEOMÉTRICOS topitos triangulo triangulares 058",
    "category": 3, 
    "price" : "$20.000", 
    "image": ["058-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 
    
    {"id": "059", 
    "title": "TOBILLERA", 
    "keywords": "TOBILLERA peyote zigzag 059",
    "category": 4, 
    "price" : "$42.000", 
    "image": ["059-01.jpg", "059-02.jpg", "059-03.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu tobillo.<br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "060", 
    "title": "MAXIARETES", 
    "keywords": "MAXIARETES ARETES GRANDES DORADO ROJO AMARILLO VERDE 060",
    "category": 3, 
    "price" : "$110.000", 
    "image": ["060-01.jpg", "060-02.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa. <br>Topos de acero dorado."}, 

    {"id": "061", 
    "title": "MAXIARETES", 
    "keywords": "MAXIARETES ARETES AZUL VERDE LILA 061",
    "category": 3, 
    "price" : "$110.000", 
    "image": ["061-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "062", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT caballero negro balin oro 062",
    "category": 7, 
    "price" : "$63.000", 
    "image": ["062-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N3mm."}, 

    {"id": "063", 
    "title": "COLLAR CHOKER CON ORO LAMINADO", 
    "keywords": "COLLAR CHOKER INICIAL CON ORO LAMINADO dije letra 063",
    "category": 2, 
    "price" : "$30.000", 
    "image": ["063-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Sistema de cierre con herrajes de acero dorado. <br>Medida aproximada del collar entre 35 a 37 cm, con extensión de cadena. <br>Letra inicial de nácar."}, 

    {"id": "064", 
    "title": "MAXIARETES CAYENA", 
    "keywords": "MAXIARETES CAYENA aretes 064",
    "category": 3, 
    "price" : "$150.000", 
    "image": ["064-01.jpg", "064-02.jpg", "064-03.jpg"],
    "description": "Inspirados en la flor de bonche y su color intenso rojo que adorna los patios y terrazas de las casas de nuestra región sabanera.<br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "065", 
    "title": "MAXIARETES CIELO INFINITO", 
    "keywords": "MAXIARETES CIELO INFINITO aretes cielo azul 065",
    "category": 3, 
    "price" : "$110.000", 
    "image": ["065-01.jpg", "065-02.jpg"],
    "description": "Inspirados en la inmensidad del cielo y sus colores.<br><br><b>Materiales:</b>Mostacilla japonesa. <br>Topos de acero dorado."}, 

    {"id": "066", 
    "title": "SET DE PULSERAS CON ORO 18KT", 
    "keywords": "SET DE PULSERAS CON ORO 18KT peyote balin oro caballero hombre 067",
    "category": 7, 
    "price" : "$65.000", 
    "image": ["066-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N3mm."}, 
    
    {"id": "067", 
    "title": "PULSERA CON ORO 18KT", 
    "keywords": "PULSERA CON ORO 18KT caballero hombre 067",
    "category": 7, 
    "price" : "$92.000", 
    "image": ["067-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Hilo coreano. <br>Dos (2) balines de oro 18 quilates tamaño N3mm.<br>Un (1) balin de oro 18 quilates tamaño N4mm."}, 

    {"id": "068", 
    "title": " SET CADENA Y ARETES ADVOCACIÓN VIRGEN", 
    "keywords": " SET DE COLLAR Y ARETES RELIGIOSO dije virgen milagrosa 068 ADVOCACIÓN VIRGEN",
    "category": 2, 
    "price" : "$45.000", 
    "image": ["068-01.jpg"],
    "description": "Se elaboran las advocaciones de la Virgen.<br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Cadena de acero dorado (los tejidos varian según disponibilidad). Medida. Aproximada 40 cm."}, 

    {"id": "069", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS 069",
    "category": 1, 
    "price" : "$68.000", 
    "image": ["069-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "070", 
    "title": " PULSERA CON ORO 18 KT", 
    "keywords": " PULSERA CON ORO 18 KT balin oro 070",
    "category": 1, 
    "price" : "$40.000", 
    "image": ["070-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Un(1) balin de oro 18 quilates tamaño N3mm."}, 

    {"id": "071", 
    "title": "CHOKER", 
    "keywords": "CHOKER CORAZON COLLAR 071",
    "category": 2, 
    "price" : "$35.000", 
    "image": ["071-01.jpg", "071-02.jpg"],
    "description": "Sistema de cierre con broche y extensión de cadena para graduar a tu cuello.<br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado.<br>Herrajes de acero dorado."}, 
    
    {"id": "072", 
    "title": "PULSERA", 
    "keywords": "PULSERA caballero hombre 072",
    "category": 7, 
    "price" : "$15.000", 
    "image": ["072-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "073", 
    "title": "TOBILLERA", 
    "keywords": "TOBILLERA PIE 073",
    "category": 4, 
    "price" : "$30.000", 
    "image": ["073-01.jpg", "073-02.jpg", "073-03.jpg", "073-04.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu tobillo.<br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 
    
    {"id": "074", 
    "title": "ARETES TOPOS GEOMÉTRICOS", 
    "keywords": "ARETES TOPOS GEOMÉTRICOS 074",
    "category": 3, 
    "price" : "$15.000", 
    "image": ["074-01.jpg", "074-02.jpg", "074-03.jpg", "074-04.jpg", "074-05.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "075", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS negro caballero hombre 075",
    "category": 7, 
    "price" : "$38.000", 
    "image": ["075-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "076", 
    "title": "ARETES HOJAS DE OTOÑO", 
    "keywords": "ARETES HOJAS DE OTOÑO 076",
    "category": 3, 
    "price" : "$40.000", 
    "image": ["076-01.jpg", "076-02.jpg", "076-03.jpg", "076-04.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 
    
    {"id": "077", 
    "title": "ANILLO PAISAJE DE VERANERAS", 
    "keywords": "ANILLO PAISAJE DE VERANERAS 077",
    "category": 5, 
    "price" : "$45.000", 
    "image": ["077-01.jpg"],
    "description": "Se realiza a la medida del cliente. <br><br><b>Materiales:</b><br>Mostacilla japonesa."}, 

    {"id": "078", 
    "title": "TOBILLERA BANDERAS", 
    "keywords": "TOBILLERA BANDERAS paises viaje viajar 078",
    "category": 4, 
    "price" : "$40.000", 
    "image": ["078-01.jpg"],
    "description": "Se elaboran con las banderas de los países que has visitado o anhelas visitar.<br><br>Sistema de cierre con nudo corredizo para graduar a tu tobillo.<br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "079", 
    "title": "SET DE CADENA Y ARETES", 
    "keywords": "SET DE CADENA Y ARETES dije flor girasol 079",
    "category": 2, 
    "price" : "$45.000", 
    "image": ["079-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado.<br>Cadena de acero dorado. Medida aproximada de 40cm. (Los tejidos varian según disponibilidad)."}, 

    {"id": "080", 
    "title": "MAXIARETES", 
    "keywords": "MAXIARETES aretes hexagonos largos 080",
    "category": 3, 
    "price" : "$65.000", 
    "image": ["080-01.jpg", "080-02.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "081", 
    "title": "ARETES TOPOS GEOMÉTRICOS", 
    "keywords": "ARETES TOPOS GEOMÉTRICOS 081",
    "category": 3, 
    "price" : "$30.000", 
    "image": ["081-01.jpg", "081-02.jpg", "081-03.jpg", "081-04.jpg", "081-05.jpg", "081-06.jpg", "081-07.jpg", "081-08.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "082", 
    "title": "SET DE PULSERAS ESCAPULARIO", 
    "keywords": "SET DE PULSERAS ESCAPULARIO dije cruz sagrado corazon 082",
    "category": 1, 
    "price" : "$65.000", 
    "image": ["082-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "083", 
    "title": "PULSERA", 
    "keywords": "PULSERA PEYOTE 083",
    "category": 1, 
    "price" : "$37.000", 
    "image": ["083-01.jpg", "083-02.jpg", "083-03.jpg", "083-04.jpg", "083-05.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "084", 
    "title": "TOBILLERA", 
    "keywords": "TOBILLERA CORAZONES 084",
    "category": 4, 
    "price" : "$45.000", 
    "image": ["084-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu tobillo. <br><br><b>Materiales:</b><br>Mostacilla japonesa. <br>Hilo coreano."}, 

    {"id": "085", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS negro caballero hombre 085",
    "category": 7, 
    "price" : "$33.000", 
    "image": ["085-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "086", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS mariposa naranja 086",
    "category": 1, 
    "price" : "$53.000", 
    "image": ["086-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "087", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS mariposa naranja lila 087",
    "category": 1, 
    "price" : "$48.000", 
    "image": ["087-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo coreano.<br>Hilos con brillo."}, 

    {"id": "088", 
    "title": "PULSERA ESCAPULARIO", 
    "keywords": "PULSERA ESCAPULARIO dije cruz sagrado corazon 088",
    "category": 1, 
    "price" : "$35.000", 
    "image": ["088-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo coreano."}, 

    {"id": "089", 
    "title": " PULSERA CORAZÓN", 
    "keywords": " PULSERA CORAZÓN corazon amor y amistad 089",
    "category": 1, 
    "price" : "$18.000", 
    "image": ["089-01.jpg", "089-02.jpg", "089-03.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "090", 
    "title": "PULSERA CON ORO 18 KT", 
    "keywords": "PULSERA MARIPOSA CON ORO 18 KT 090",
    "category": 1, 
    "price" : "$70.000", 
    "image": ["090-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado.<br>Dos (2) balines de oro 18 quilates tamaño N3mm."}, 

    {"id": "091", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT dije cruz peyote 091",
    "category": 1, 
    "price" : "$113.000", 
    "image": ["091-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Dos (2) balines de oro 18 quilates tamaño N4mm."}, 

    {"id": "092", 
    "title": "PULSERA CON ORO 18KT", 
    "keywords": "PULSERA CON ORO 18 KT dije sagrado corazon 092",
    "category": 1, 
    "price" : "$65.000", 
    "image": ["092-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Dos (2) balines de oro 18 quilates tamaño N3mm."}, 

    {"id": "093", 
    "title": "PULSERA CON ORO 18 KT", 
    "keywords": "PULSERA CON ORO 18 KT caballero hombre 093",
    "category": 7, 
    "price" : "$40.000", 
    "image": ["093-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N3mm."}, 
    
    {"id": "094", 
    "title": "SET DE PULSERAS CON ORO 18KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT azul cielo corazon 094",
    "category": 1, 
    "price" : "$119.000", 
    "image": ["094-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Tres (3) balines de oro 18 quilates tamaño N3mm."}, 

    {"id": "095", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT dije sagrado corazon 095",
    "category": 1, 
    "price" : "$104.000", 
    "image": ["095-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado.<br>2 balines de oro 18 quilates N°3mm."}, 

    {"id": "096", 
    "title": "PULSERA MASCOTA CON ORO 18KT", 
    "keywords": "PULSERA MASCOTA CON ORO 18KT dije perro perrito 096",
    "category": 1, 
    "price" : "$70.000", 
    "image": ["096-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br>Se personaliza la carita de la mascota. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado.<br>Hilos con brillo<br>Dos (2) balines de oro 18 quilates tamaño n3mm."}, 

    {"id": "097", 
    "title": "SET DE PULSERAS ESCAPULARIO", 
    "keywords": "SET DE PULSERAS ESCAPULARIO dije sagrado corazon 097",
    "category": 1, 
    "price" : "$64.000", 
    "image": ["097-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "098", 
    "title": "MAXIARETES UNA CASA EN LA VILLA", 
    "keywords": "MAXIARETES UNA CASA EN LA VILLA aretes hexagono colorido 098",
    "category": 3, 
    "price" : "$80.000", 
    "image": ["098-01.jpg", "098-02.jpg"],
    "description": "Inspirados en la casa colorida ubicada en el municipio de La Villa San Benito Abad.<br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "099", 
    "title": "SET DE PULSERAS CON ORO 18KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT 099",
    "category": 1, 
    "price" : "$156.000", 
    "image": ["099-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado.<br>Seis (6) balines de oro 18 quilates tamaño N3mm."}, 

    {"id": "100", 
    "title": " COLLAR CHOKER SAGRADO CORAZÓN", 
    "keywords": " COLLAR CHOKER ESCAPULARIO sagrado corazon 100",
    "category": 2, 
    "price" : "$40.000", 
    "image": ["100-01.jpg", "100-02.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Sistema de cierre con herrajes de acero dorado. <br>Medida aproximada del collar entre 36 a 38 cm."}, 
    
    {"id": "101", 
    "title": "CAJA DE REGALO", 
    "keywords": "CAJA DE REGALO DETALLE CAJA DECORADA scrunchie hatsu 101",
    "category": 9, 
    "price" : "$28.000", 
    "image": ["101-01.jpg"],
    "description": "Caja de regalo con joyas tejidas a mano por artesanos de la ciudad de Sincelejo - Sucre.<br><br>Complementamos con otros productos de marcas Sucreñas o Nacionales. <br><br><b>Contiene:</b><br>1. Aretes tipos con forma triangular: $ 15.000.<br>2. Scrunch talla M diseñado por Diana Design: $7.000.<br>3. Te Hatsú: $6.000.<br><br>Se obsequia la caja decorativa que incluye: lazo en tela, tarjeta escrita en máquina, aplique floral seco."}, 

    {"id": "102", 
    "title": "CAJA DE REGALO", 
    "keywords": "CAJA DE REGALO DETALLE CAJA DECORADA topos 102",
    "category": 9, 
    "price" : "$40.000", 
    "image": ["102-01.jpg", "102-02.jpg"],
    "description": "Caja de regalo con joyas tejidas a mano por artesanos de la ciudad de Sincelejo - Sucre.<br><br>Complementamos con otros productos de marcas Sucreñas o Nacionales.<br><br><b>Contiene:</b><br>1. Aretes tipos con forma hexagonal $30.000.<br>2. Scrunch talla L diseñado por Diana Design: $10.000.<br><br>Se obsequia la caja decorativa que incluye: lazo en tela, tarjeta escrita en máquina, aplique floral seco."}, 

    {"id": "103", 
    "title": "COLLAR CHOKER ESCAPULARIO", 
    "keywords": "COLLAR CHOKER ESCAPULARIO dije cruz sagrado corazon 103",
    "category": 2, 
    "price" : "$45.000", 
    "image": ["103-01.jpg"],
    "description": "<b>Materiales:</b>Mostacilla japonesa.<br>Sistema de cierre con herrajes de acero dorado. <br>Medida aproximada del collar entre 36 a 38 cm."}, 

    {"id": "104", 
    "title": "ANILLO CAÑANDONGA FLORECIDA", 
    "keywords": "ANILLO CAÑANDONGA FLORECIDA flor 104",
    "category": 5, 
    "price" : "$45.000", 
    "image": ["104-01.jpg"],
    "description": "Inspirado en la Cañandonga Florecida y el paisaje de nuestro Departamento Sucre.<br><br>Se realiza a la medida del cliente. <br><br><b>Materiales:</b><br>Mostacilla japonesa."}, 

    {"id": "105", 
    "title": " SET DE PULSERAS", 
    "keywords": " SET DE PULSERAS tila 3 filas peyote 105",
    "category": 1, 
    "price" : "$68.000", 
    "image": ["105-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "106", 
    "title": "PULSERA CON ORO 18KT", 
    "keywords": "PULSERA CON ORO 18KT infantil niño niña 106",
    "category": 8, 
    "price" : "$40.000", 
    "image": ["106-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b>Mostacilla japonesa. <br>Hilo coreano. <br>Un (1) balin de oro 18 quilates tamaño N3mm."}, 

    {"id": "107", 
    "title": "PULSERA", 
    "keywords": "PULSERA negro 107",
    "category": 1, 
    "price" : "$25.000", 
    "image": ["107-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "108", 
    "title": "JOYAS PARA COMPARTIR", 
    "keywords": "JOYAS PARA COMPARTIR pareja esposos novios enamorados 108",
    "category": 10, 
    "price" : "$40.000", 
    "image": ["108-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "109", 
    "title": "ANILLO SAGRADO CORAZÓN", 
    "keywords": "ANILLO SAGRADO CORAZÓN corazon 109",
    "category": 5, 
    "price" : "$40.000", 
    "image": ["109-01.jpg"],
    "description": "Se realiza a la medida del cliente. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>"}, 

    {"id": "110", 
    "title": "TOBILLERA", 
    "keywords": "TOBILLERA roja 110",
    "category": 4, 
    "price" : "$20.000", 
    "image": ["110-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu tobillo<br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo coreano."}, 

    {"id": "111", 
    "title": "PULSERA", 
    "keywords": "PULSERA delgada 111",
    "category": 7, 
    "price" : "$15.000", 
    "image": ["111-01.jpg", "111-02.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "112", 
    "title": "PULSERA", 
    "keywords": "PULSERA COLORES PULSERA ARCO IRIS 112",
    "category": 1, 
    "price" : "$20.000", 
    "image": ["112-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo coreano."}, 
    
    {"id": "113", 
    "title": "ARETES TOPOS GEOMÉTRICOS", 
    "keywords": "ARETES TOPOS GEOMÉTRICOS 113",
    "category": 3, 
    "price" : "$45.000", 
    "image": ["113-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 
    
    {"id": "114", 
    "title": "PULSERA COLOMBIA", 
    "keywords": "PULSERA COLOMBIA colombiana tricolor 114",
    "category": 1, 
    "price" : "$32.000", 
    "image": ["114-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "115", 
    "title": "MAXIARETES", 
    "keywords": "MAXIARETES ARETES AZULES 115",
    "category": 3, 
    "price" : "$50.000", 
    "image": ["115-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "116", 
    "title": "CAJA DE REGALO", 
    "keywords": "CAJA DE REGALO scrunchie 116",
    "category": 9, 
    "price" : "$28.000", 
    "image": ["116-01.jpg", "116-02.jpg"],
    "description": "Caja de regalo con joyas tejidas a mano por artesanos de la ciudad de Sincelejo - Sucre.<br><br>Complementamos con otros productos de marcas Sucreñas o Nacionales. <br><br><b>Contiene:</b><br>1. Pulsera tejida a mano: $18.000. <br>2. Scrunch talla M de la marca Diana Designs: $10.000."}, 

    {"id": "117", 
    "title": "PULSERA CON ORO 18KT", 
    "keywords": "PULSERA CON ORO 18KT dije letra inicial j 117",
    "category": 1, 
    "price" : "$60.000", 
    "image": ["117-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Dos (2) balines de oro 18 quilates tamaño N3mm."}, 

    {"id": "118", 
    "title": " PULSERA CON ORO 18KT", 
    "keywords": " PULSERA CON ORO 18 KT colores arco iris 118",
    "category": 1, 
    "price" : "$52.000", 
    "image": ["118-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa. <br>Hilo coreano.<br>Un (1) balin de oro 18 quilates tamaño N4mm."}, 

    {"id": "119", 
    "title": "ANILLO", 
    "keywords": "ANILLO ROMBO NEGRO AZUL 119",
    "category": 5, 
    "price" : "$30.000", 
    "image": ["119-01.jpg", "119-02.jpg"],
    "description": "Se realiza a la medida del cliente. <br><br><b>Materiales:</b><br>Mostacilla japonesa."}, 

    {"id": "120", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS corazon dorado tila una fila 120",
    "category": 1, 
    "price" : "$31.000", 
    "image": ["120-01.jpg", "120-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "121", 
    "title": "PULSERA", 
    "keywords": "PULSERA PEYOTE PULSERA ANCHA DROPS GOTAS 121",
    "category": 1, 
    "price" : "$65.000", 
    "image": ["121-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 
    
    {"id": "122", 
    "title": "PULSERA", 
    "keywords": "PULSERA 2 FILAS 122",
    "category": 1, 
    "price" : "$20.000", 
    "image": ["122-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "123", 
    "title": "MAXIARETES", 
    "keywords": "MAXIARETES aretes animal print 123",
    "category": 3, 
    "price" : "$80.000", 
    "image": ["123-01.jpg", "123-02.jpg", "123-03.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa. <br>Topos en acero dorado."}, 

    {"id": "124", 
    "title": "PULSERA", 
    "keywords": "PULSERA peyote 124",
    "category": 1, 
    "price" : "$27.000", 
    "image": ["124-01.jpg", "124-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "125", 
    "title": "MAXIARETES FLOR DE COCORILLA", 
    "keywords": "MAXIARETES FLOR DE COCORILLA aretes flor cocorilla 125",
    "category": 3, 
    "price" : "$60.000", 
    "image": ["125-01.jpg", "125-02.jpg"],
    "description": "Inspirados en la pinta del trenzado de piezas de la Etnia Zenue, Flor de Cocorilla.<br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "126", 
    "title": "ARETES CORAZÓN", 
    "keywords": "ARETES CORAZÓN corazon 126",
    "category": 3, 
    "price" : "$35.000", 
    "image": ["126-01.jpg", "126-02.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado.<br>Balines con baño dorado."}, 

    {"id": "127", 
    "title": "PULSERA", 
    "keywords": "PULSERA biscolata 127",
    "category": 7, 
    "price" : "$25.000", 
    "image": ["127-01.jpg", "127-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "128", 
    "title": "MAXIARETES LA MARQUESA", 
    "keywords": "MAXIARETES LA MARQUESA aretes la marquesa 128",
    "category": 3, 
    "price" : "$60.000", 
    "image": ["128-01.jpg", "128-02.jpg"],
    "description": "Inspirada en la encantadora Mompox, el portal de la Marquesa, con vista hacia el río, se caracteriza por sus ventanas e inmensos portales, techos altos y una arquitectura colonial.<br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "129", 
    "title": "ARETES TOPOS GEOMÉTRICOS", 
    "keywords": "MAXIARETES TOPOS GEOMÉTRICOS aretes topo grandes 129",
    "category": 3, 
    "price" : "$40.000", 
    "image": ["129-01.jpg", "129-02.jpg", "129-03.jpg", "129-04.jpg", "129-05.jpg", "129-06.jpg", "129-07.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 
    
    {"id": "130", 
    "title": "PULSERA", 
    "keywords": "PULSERA INFANTIL NIÑA CORAZONES CORAZON 130",
    "category": 8, 
    "price" : "$32.000", 
    "image": ["130-01.jpg", "130-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo coreano."}, 
    
    {"id": "131", 
    "title": "COLLAR CHOKER CON ORO LAMINADO", 
    "keywords": "COLLAR CHOKER CON ORO LAMINADO 131",
    "category": 2, 
    "price" : "$35.000", 
    "image": ["131-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Sistema de cierre con herrajes de acero dorado.<br>Medida aproximada de choker entre 35 a 37 cm. <br>2 balines de oro laminado N3mm.<br>Piedra natural Turquesa Africana: Favorece el descanso y la vitalidad."}, 

    {"id": "132", 
    "title": "SET DE PULSERAS CON ORO LAMINADO", 
    "keywords": "SET DE PULSERAS CON ORO LAMINADO 132",
    "category": 1, 
    "price" : "$60.000", 
    "image": ["132-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Hilos con brillo.<br>Hilo encerado. <br>Tres (3) balines de oro laminado tamaño N3mm. <br>Piedra natural turquesa africana."}, 

    {"id": "133", 
    "title": "PULSERA OJO TURCO", 
    "keywords": "PULSERA rombo ojo turco 133",
    "category": 1, 
    "price" : "$27.000", 
    "image": ["133-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo coreano."}, 

    {"id": "134", 
    "title": "JOYAS PARA COMPARTIR: ORO 18 KT", 
    "keywords": "JOYAS PARA COMPARTIR: ORO 18 KT pareja roja balin oro 134",
    "category": 10, 
    "price" : "$80.000", 
    "image": ["134-01.jpg", "134-02.jpg"],
    "description": ""}, 

    {"id": "135", 
    "title": "PULSERA", 
    "keywords": "PULSERA cilindro cuero 135",
    "category": 7, 
    "price" : "$22.000", 
    "image": ["135-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Hilo encerado. <br>Cuero natural. <br>Mostacilla japonesa."}, 

    {"id": "136", 
    "title": "MAXIARETES CIELO INFINITO", 
    "keywords": "MAXIARETES CIELO INFINITO aretes cielo aretes azules 136",
    "category": 3, 
    "price" : "$60.000", 
    "image": ["136-01.jpg", "136-02.jpg"],
    "description": "Inspirados en la inmensidad del cielo y sus colores.<br><br><b>Materiales:</b>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "137", 
    "title": "SET DE PULSERAS CON ORO 18KT", 
    "keywords": "SET DE PULSERAS CON ORO 18KT 137",
    "category": 1, 
    "price" : "$224.000", 
    "image": ["137-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo. <br>Hilo encerado. <br>Nueve (9) balines de oro 18 quilates tamaño N3mm."}, 

    {"id": "138", 
    "title": "MAXIARETES", 
    "keywords": "MAXIARETES aretes hexagonos grandes 138",
    "category": 3, 
    "price" : "$200.000", 
    "image": ["138-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "139", 
    "title": "MAXIARETES", 
    "keywords": "MAXIARETES aretes hexagonos grandes fucsia topo 139",
    "category": 3, 
    "price" : "$60.000", 
    "image": ["139-01.jpg", "139-02.jpg", "139-03.jpg", "139-04.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "140", 
    "title": "COLLAR CHOKER SAGRADO CORAZÓN", 
    "keywords": "COLLAR CHOKER SAGRADO CORAZON 140",
    "category": 2, 
    "price" : "$30.000", 
    "image": ["140-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Sistema de cierre con herrajes de acero dorado.<br>Medida aproximada del collar entre 35 a 37 cm, con extensión de cadena."}, 

    {"id": "141", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS PULSERAS ROJA CORAZON 141",
    "category": 1, 
    "price" : "$48.000", 
    "image": ["141-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca.<br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "142", 
    "title": "PULSERA SAGRADO CORAZÓN", 
    "keywords": "PULSERA SAGRADO CORAZÓN PLACA 142",
    "category": 1, 
    "price" : "$35.000", 
    "image": ["142-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca.<br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo coreano. <br>Hilos con brillos."}, 
   
    {"id": "143", 
    "title": "PULSERA CORAZÓN", 
    "keywords": "PULSERA CORAZON 4 FILAS TELAR 143",
    "category": 1, 
    "price" : "$30.000", 
    "image": ["143-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo metalizado.<br>Hilo coreano."}, 

    {"id": "144", 
    "title": "JOYAS PARA COMPARTIR", 
    "keywords": "JOYAS PARA COMPARTIR 144",
    "category": 10, 
    "price" : "$50.000", 
    "image": ["144-01.jpg", "144-02.jpg", "144-03.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "145", 
    "title": "JOYAS PARA COMPARTIR", 
    "keywords": "JOYAS PARA COMPARTIR 145",
    "category": 10, 
    "price" : "$64.000", 
    "image": ["145-01.jpg", "145-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "146", 
    "title": "PULSERA", 
    "keywords": "PULSERA MARIPOSA 146",
    "category": 1, 
    "price" : "$30.000", 
    "image": ["146-01.jpg", "146-02.jpg", "146-03.jpg", "146-04.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo."}, 

    {"id": "147", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS 147 CORAZON",
    "category": 1, 
    "price" : "$43.000", 
    "image": ["147-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "148", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT 148",
    "category": 1, 
    "price" : "$63.000", 
    "image": ["148-01.jpg", "148-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N3mm."}, 

    {"id": "149", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS mariposa 149",
    "category": 1, 
    "price" : "$73.000", 
    "image": ["149-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado."}, 

    {"id": "150", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS 150 negra negro caballero hombre",
    "category": 7, 
    "price" : "$45.000", 
    "image": ["150-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "151", 
    "title": "PULSERA CON ORO 18 KT", 
    "keywords": "PULSERA CON ORO 18 KT 151 verde",
    "category": 7, 
    "price" : "$40.000", 
    "image": ["151-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa. <br>Hilo encerado.<br>Un (1) balin de oro 18 quilates tamaño N3mm."}, 

    {"id": "152", 
    "title": "SET DE PULSERA", 
    "keywords": "SET DE PULSERA 152 corazon",
    "category": 1, 
    "price" : "$71.000", 
    "image": ["152-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "153", 
    "title": "SET DE PULSERAS CON ORO LAMINADO", 
    "keywords": "SET DE PULSERAS CON ORO LAMINADO 153 sagrado corazon",
    "category": 1, 
    "price" : "$63.000", 
    "image": ["153-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b>Mostacilla japonesa.<br>Hilo encerado. <br>Dos (2) balines de oro laminado tamaño n3mm."}, 

    {"id": "154", 
    "title": "PULSERA", 
    "keywords": "PULSERA 154 mariposa",
    "category": 1, 
    "price" : "$17.000", 
    "image": ["154-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Otros hilos."}, 

    {"id": "155", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS 155",
    "category": 1, 
    "price" : "$49.000", 
    "image": ["155-01.jpg", "155-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "156", 
    "title": "ARETES TOPOS GEOMÉTRICOS", 
    "keywords": "aretes TOPOS GEOMÉTRICOS 156",
    "category": 3, 
    "price" : "$20.000", 
    "image": ["156-01.jpg", "156-02.jpg", "156-03.jpg", "156-04.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 
    
    {"id": "157", 
    "title": "PULSERA", 
    "keywords": "PULSERA ancha azul cielo peyote 157",
    "category": 1, 
    "price" : "$70.000", 
    "image": ["157-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "158", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS 158",
    "category": 1, 
    "price" : "$28.000", 
    "image": ["158-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "159", 
    "title": "ANILLO", 
    "keywords": "ANILLO gris grande 159",
    "category": 5, 
    "price" : "$50.000", 
    "image": ["159-01.jpg"],
    "description": "Se realiza a la medida del cliente. <br><br><b>Materiales:</b><br>Mostacilla japonesa."}, 

    {"id": "160", 
    "title": "PULSERA SAGRADO CORAZÓN", 
    "keywords": "PULSERA 160 sagrado corazon",
    "category": 7, 
    "price" : "$30.000", 
    "image": ["160-01.jpg", "160-02.jpg", "160-03.jpg", "160-04.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo coreano. <br>Piedras naturales."}, 

    {"id": "161", 
    "title": "JOYAS PARA COMPARTIR", 
    "keywords": "JOYAS PARA COMPARTIR pulseras pareja 161",
    "category": 1, 
    "price" : "$110.000", 
    "image": ["161-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "162", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS 162",
    "category": 1, 
    "price" : "$33.000", 
    "image": ["162-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Perla natural."}, 

    {"id": "163", 
    "title": "PULSERA", 
    "keywords": "PULSERA 163",
    "category": 1, 
    "price" : "$60.000", 
    "image": ["163-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "164", 
    "title": "CADENA CON DIJE SAGRADO CORAZÓN", 
    "keywords": "CADENA CON DIJE SAGRADO CORAZÓN 164",
    "category": 2, 
    "price" : "$37.000", 
    "image": ["164-01.jpg"],
    "description": "<b>Materiales:</b><br> Mostacilla japonesa.<br>Cadena de acero dorado, medida aproximada de 40cm. (Los tejidos varian según disponibilidad)."}, 

]

/*

    {"id": "", 
    "title": "", 
    "keywords": "",
    "category": , 
    "price" : "$", 
    "image": [".jpg"],
    "description": ""}, 

*/