intro = `<p class="c-gray">Joyas tejidas a mano por artesanos de la ciudad de Sincelejo - Sucre.</p><br>`

cuidados = `    
    <ul class='list'>    
        <li>Evita el contacto con productos químicos o de aseo en general.</li>
        <li>Las cremas, el perfume y el agua pueden alterar su color original.</li>
        <li>Evita golpear tu joya.</li>
        <li>No la uses para bañarte en piscinas o en el mar. </li>
        <li>Guárdala por separado para evitar desgaste o enredos por roce con otros accesorios.</li>
        <li>Lava tus manos antes de colocarte y quitarte las pulseras.</li>
    </ul>    
    
`

categories = [
    {"id": 1, "group": "Dama", "name": "Pulsera"},
    {"id": 2, "group": "Dama", "name": "Collar"},
    {"id": 3, "group": "Dama", "name": "Aretes"},
    {"id": 4, "group": "Dama", "name": "Tobillera"},
    {"id": 5, "group": "Dama", "name": "Anillo"},
    {"id": 6, "group": "Dama", "name": "Dije"},    
    {"id": 7, "group": "Caballero", "name": "Pulsera"},
    {"id": 6, "group": "Infantil", "name": "Pulsera"}
]

catalog = [   

    {"id": "001", 
    "title": "SET DE PULSERAS CON ORO DE 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO DE 18 KT",
    "category": 1, 
    "price" : "$53.000", 
    "image": ["001-01.jpg", "001-02.jpg", "001-03.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b> <br>Mostacilla japonesa.<br>Hilo encerado.<br>Un (1) balin de oro 18 quilates tamaño  N°3mm."},
   
    {"id": "002", 
    "title": "PULSERA CON ORO 18 KT", 
    "keywords": "PULSERA CON ORO 18 KT",
    "category": 1, 
    "price" : "$40.000", 
    "image": ["002-01.jpg", "002-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca.<br><br><b>Materiales:</b><br>Hilos con brillo.<br>Hilo encerado.<br>Un(1) balin de oro 18 quilates tamaño N3mm."}, 

    {"id": "003", 
    "title": "SET DE PULSERAS CON ORO DE 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO DE 18 KT",
    "category": 1, 
    "price" : "$82.000", 
    "image": ["003-01.jpg", "003-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N°4mm."}, 

    {"id": "004", 
    "title": "SET DE PULSERAS CON ORO DE 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO DE 18 KT",
    "category": 1, 
    "price" : "$65.000", 
    "image": ["004-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N°3mm."}, 

    {"id": "005", 
    "title": "PULSERA CON ORO 18 KT", 
    "keywords": "PULSERA CON ORO 18 KT",
    "category": 1, 
    "price" : "$52.000", 
    "image": ["005-01.jpg", "005-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N°4mm."}, 

    {"id": "006", 
    "title": "SET DE PULSERAS CON ORO DE 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO DE 18 KT",
    "category": 1, 
    "price" : "$110.000", 
    "image": ["006-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Tres (3) balines de oro 18 quilates tamaño N°3mm."}, 

    {"id": "007", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS DIJE CRUZ",
    "category": 1, 
    "price" : "$36.000", 
    "image": ["007-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "008", 
    "title": "PULSERA", 
    "keywords": "PULSERA DIJE MANO OJO",
    "category": 1, 
    "price" : "$35.000", 
    "image": ["008-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo coreano."}, 
    
    {"id": "009", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT CORAZON PEYOTE 5 BALINES",
    "category": 1, 
    "price" : "$218.000", 
    "image": ["009-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa. <br>Hilos con brillo. <br>Hilo encerado. <br>Siete (7) balines de oro 18 quilates tamaño N3mm.*"}, 

    {"id": "010", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS DIJE CRUZ SAGRADO CORAZON",
    "category": 1, 
    "price" : "$43.000", 
    "image": ["010-01.jpg", "010-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "011", 
    "title": "TOBILLERA CON ORO 18 KT", 
    "keywords": "TOBILLERA CON ORO 18 KT MARIPOSA FUCSIA AZUL",
    "category": 4, 
    "price" : "$115.000", 
    "image": ["011-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu tobillo. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo coreano. <br>Cuatro (4) balines de oro 18 quilates tamaño N3mm."}, 

    {"id": "012", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT CORAZON",
    "category": 1, 
    "price" : "$81.000", 
    "image": ["012-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N4mm."}, 

    {"id": "013", 
    "title": "SET DE PULSERAS CON ORO 18 KT",
    "keywords": "SET DE PULSERAS CON ORO 18 KT", 
    "category": 1, 
    "price" : "$279.000", 
    "image": ["013-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Siete (7) balines de oro 18 quilates tamaño N4mm."}, 

    {"id": "014", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT CORAZON",
    "category": 1, 
    "price" : "$98.000", 
    "image": ["014-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Hilos con brillo. <br>Dos (2) balines de oro 18 quilates tamaño N3mm."}, 

    {"id": "015", 
    "title": "PULSERA CON ORO 18 KT", 
    "keywords": "PULSERA COLORIDA CON ORO 18 KT COLORINCHE",
    "category": 1, 
    "price" : "$80.000", 
    "image": ["015-01.jpg", "015-02.png"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo coreano.<br>Tres (3) balines de oro 18 quilates tamaño N3mm."}, 

    {"id": "016", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT",
    "category": 1, 
    "price" : "$93.000", 
    "image": ["016-01.jpg", "016-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Tres (3) balines de oro 18 quilates tamaño N3mm."}, 

    {"id": "017", 
    "title": "PULSERA CON ORO 18 KT", 
    "keywords": "PULSERA CON ORO 18 KT TEJIDO HILO ENCERADO ROJO",
    "category": 1, 
    "price" : "$80.000", 
    "image": ["017-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Hilo encerado. <br>Tres (3) balines de oro 18 quilates tamaño N3mm."}, 

    {"id": "018", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT",
    "category": 1, 
    "price" : "$83.000", 
    "image": ["018-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N4mm."}, 

    {"id": "019", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS PEYOTE COLORES VIBRANTES NARANJA",
    "category": 1, 
    "price" : "$45.000", 
    "image": ["019-01.jpg", "019-02.jpg", "019-03.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "020", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS PEYOTE ROJO TILA ROJA",
    "category": 1, 
    "price" : "$40.000", 
    "image": ["020-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "021", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS",
    "category": 1, 
    "price" : "$36.000", 
    "image": ["021-01.jpg", "021-02.jpg", "021-03.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "022", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS MORADO LILA CORAZON",
    "category": 1, 
    "price" : "$41.000", 
    "image": ["022-01.jpg", "022-02.jpg", "022-03.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "023", 
    "title": "PULSERA CORAZÓN", 
    "keywords": "PULSERA CORAZÓN OSCURA LILA MORADO",
    "category": 1, 
    "price" : "$25.000", 
    "image": ["023-01.jpg", "023-02.jpg", "023-03.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "024", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS PERLA ENFILADA PEYOTE",
    "category": 1, 
    "price" : "$45.000", 
    "image": ["024-01.jpg", "024-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Perla natural."}, 

    {"id": "025", 
    "title": "PULSERA", 
    "keywords": "PULSERA DROPS LAGRIMAS PEYOTE",
    "category": 1, 
    "price" : "$35.000", 
    "image": ["025-01.jpg", "025-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "026", 
    "title": "PULSERA CORAZONES", 
    "keywords": "PULSERA CORAZONES TRES 3",
    "category": 1, 
    "price" : "$26.000", 
    "image": ["026-01.jpg", "026-02.jpg", "026-03.jpg", "026-04.jpg", "026-05.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "027", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS SWAROSKI TILA LILA ENFILADA",
    "category": 1, 
    "price" : "$48.000", 
    "image": ["027-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Aplique de cristal de Swaroski."}, 

    {"id": "028", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS TELAR NUDE",
    "category": 1, 
    "price" : "$61.000", 
    "image": ["028-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "029", 
    "title": "PULSERAS", 
    "keywords": "PULSERA COLORIDA COLORINCHE 1 FILA",
    "category": 1, 
    "price" : "$15.000", 
    "image": ["029-01.jpg", "029-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "030", 
    "title": "SET DE COLLAR Y ARETES", 
     "keywords": "SET DE COLLAR Y ARETES DIJE GATO",
    "category": 2, 
    "price" : "$53.000", 
    "image": ["030-01.jpg", "030-02.jpg", "030-03.jpg", "030-04.jpg", "030-05.jpg"],
    "description": "Elaboramos los rostros de mascotas que el cliente solicite. <br><br><b>*Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado.<br>Cadena de acero dorado medida aproximada 40cm de largo. (Los tejidos varian según disponibilidad)."}, 
    
    {"id": "031", 
    "title": "ARETES TOPO GEOMÉTRICOS", 
    "keywords": "ARETES TOPO GEOMÉTRICOS DORADO OSCURO BLANCO",
    "category": 3, 
    "price" : "$55.000", 
    "image": ["031-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "032", 
    "title": "PULSERA CON INICIAL",
    "keywords": "PULSERA CON INICIAL LETRA DIJE",
    "category": 1, 
    "price" : "$20.000", 
    "image": ["032-01.jpg", "032-02.jpg", "032-03.jpg", "032-04.jpg", "032-05.jpg", "032-06.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "033", 
    "title": "PULSERA MASCOTA", 
    "keywords": "PULSERA MASCOTA DIJE PERRO DIJE PERRITO ",
    "category": 1, 
    "price" : "$30.000", 
    "image": ["033-01.jpg", "033-02.jpg", "033-03.jpg", "033-04.jpg", "033-05.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Se personaliza la carita de la mascota. <br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "034", 
    "title": "ANILLO", 
    "keywords": "ANILLO",
    "category": 5, 
    "price" : "$30.000", 
    "image": ["034-01.jpg"],
    "description": "Se realiza a la medida del cliente.<br><br><b>Materiales:</b><br>Mostacilla japonesa."}, 
    
    {"id": "035", 
    "title": "MAXIARETES", 
    "keywords": "ARETES MAXIARETES VERDE DORADO",
    "category": 3, 
    "price" : "$60.000", 
    "image": ["035-01.jpg", "035-02.jpg", "035-03.jpg", "035-04.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 
      
    {"id": "036", 
    "title": "MAXIARETES", 
    "keywords": "ARETES MAXIARETES COLORES",
    "category": 3, 
    "price" : "$80.000", 
    "image": ["036-01.jpg", "036-02.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 
     
    {"id": "037", 
    "title": "MAXIARETES DESDE LA MONTAÑA", 
    "keywords": "MAXIARETES DESDE LA MONTAÑA ARETES VERDE",
    "category": 3, 
    "price" : "$80.000", 
    "image": ["037-01.jpg"],
    "description": "Inspirados en la experiencia de viaje hacia  la Reserva Forestal de de Coraza, Chalan-Sucre.<br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "038", 
    "title": "SET DE ANILLOS", 
    "keywords": "SET DE ANILLOS ANILLO DELGADO",
    "category": 5, 
    "price" : "$38.000", 
    "image": ["038-01.jpg"],
    "description": "Se realiza a la medida del cliente. <br><br><b>Materiales:</b><br>Mostacilla japonesa."}, 

    {"id": "039", 
    "title": "ANILLO", 
    "keywords": "ANILLO GRANDE NEGRO ROJO",
    "category": 5, 
    "price" : "$45.000", 
    "image": ["039-01.jpg"],
    "description": "Se realiza a la medida del cliente. <br><br><b>Materiales:</b><br>Mostacilla japonesa."}, 

    {"id": "040", 
    "title": "PULSERA", 
    "keywords": "PULSERA PEYOTE ROMBOS HOMBRE CABALLERO",
    "category": 7, 
    "price" : "$32.000", 
    "image": ["040-01.jpg", "040-02.jpg", "040-03.jpg", "040-04.jpg", "040-05.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "041", 
    "title": "MAXIARETES VERANERAS", 
    "keywords": "MAXIARETES VERANERAS ARETES FLOR FUCSIA FLORES",
    "category": 3, 
    "price" : "$110.000", 
    "image": ["041-01.jpg"],
    "description": "Inspirados en la veranera que con su majestuoso color fucsia, embellece nuestras casas y paisajes de la región.<br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "042", 
    "title": "PULSERA", 
    "keywords": "PULSERA NOMBRE TELAR",
    "category": 1, 
    "price" : "$25.000", 
    "image": ["042-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "043", 
    "title": "PULSERA MARIPOSA", 
    "keywords": "PULSERA MARIPOSA",
    "category": 1, 
    "price" : "$30.000", 
    "image": ["043-01.jpg", "043-02.jpg"], 
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo coreano."}, 

    {"id": "044", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS PASTEL TILA",
    "category": 1, 
    "price" : "$38.000", 
    "image": ["044-01.jpg", "044-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado.<br>"}, 

    {"id": "045", 
    "title": "MAXIARETES", 
    "keywords": "ARETES MAXIARETES FLOR DORADO AZUL MORADO LILA",
    "category": 3, 
    "price" : "$80.000", 
    "image": ["045-01.jpg", "045-02.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "046", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT ZIGZAG PEYOTE",
    "category": 1, 
    "price" : "$160.000", 
    "image": ["046-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Cinco (5) balines de oro 18 quilates tamaño N3mm."}, 

    {"id": "047", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT TONOS TIERRA",
    "category": 1, 
    "price" : "$63.000", 
    "image": ["047-01.jpg", "047-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N3mm."}, 

    {"id": "048", 
    "title": "PULSERA CON ORO 18 KT", 
    "keywords": "PULSERA CON ORO 18 KT 2 CORAZONES BALIN DELGADA ANCHA",
    "category": 1, 
    "price" : "$49.000", 
    "image": ["048-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N3mm."}, 

    {"id": "049", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS CORAZONES DE COLORES CORAZON",
    "category": 1, 
    "price" : "$64.000", 
    "image": ["049-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Hilo coreano."}, 

    {"id": "050", 
    "title": "ANILLO", 
    "keywords": "ANILLO NEGRO ROMBO",
    "category": 5, 
    "price" : "$35.000", 
    "image": ["050-01.jpg", "050-02.jpg"],
    "description": "Se realiza a la medida del cliente. <br><br><b>Materiales:</b><br>Mostacilla japonesa."}, 

    {"id": "051", 
    "title": "PULSERA", 
    "keywords": "PULSERA CORAZON CORAZONES DE COLORES",
    "category": 1, 
    "price" : "$40.000", 
    "image": ["051-01.jpg", "051-02.jpg", "051-03.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo coreano."}, 

    {"id": "052", 
    "title": "ANILLO", 
    "keywords": "ANILLO",
    "category": 5, 
    "price" : "$25.000", 
    "image": ["052-01.jpg", "052-02.jpg", "052-03.jpg", "052-04.jpg"],
    "description": "Se realiza a la medida del cliente. <br><br><b>Materiales:</b><br>Mostacilla japonesa."}, 

    {"id": "053", 
    "title": "PULSERA RELIGIOSA", 
    "keywords": "PULSERA RELIGIOSA DIJE VIRGEN GUADALUPE GUADALUPANA",
    "category": 1, 
    "price" : "$40.000", 
    "image": ["053-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo."}, 

]

/*

    {"id": "", 
    "title": "", 
    "category": , 
    "price" : "$", 
    "image": [".jpg"],
    "description": ""}, 

*/

