intro = `<p class="c-gray">Joyas tejidas a mano por artesanos de la ciudad de Sincelejo - Sucre.</p><br>`

cuidados = `    
    <ul class='list'>    
        <li>Evita el contacto con productos químicos o de aseo en general.</li>
        <li>Las cremas, el perfume y el agua pueden alterar su color original.</li>
        <li>Evita golpear tu joya.</li>
        <li>No la uses para bañarte en piscinas o en el mar. </li>
        <li>Guárdala por separado para evitar desgaste o enredos por roce con otros accesorios.</li>
        <li>Lava tus manos antes de colocarte y quitarte las pulseras.</li>
    </ul>    
    
`

categories = [
    {"id": 1, "group": "Dama", "name": "Pulsera"},
    {"id": 2, "group": "Dama", "name": "Collar"},
    {"id": 3, "group": "Dama", "name": "Aretes"},
    {"id": 4, "group": "Dama", "name": "Tobillera"},
    {"id": 5, "group": "Dama", "name": "Anillo"},
    {"id": 6, "group": "Dama", "name": "Dije"},    
    {"id": 7, "group": "Caballero", "name": "Pulsera"},
    {"id": 8, "group": "Infantil", "name": "Pulsera"},
    {"id": 9, "group": "Cajas de regalo", "name": "CAJAS DE REGALO"},
    {"id": 10, "group": "Joyas para compartir", "name": "JOYAS PARA COMPARTIR"}
]

catalog = [   

    {"id": "001", 
    "title": "SET DE PULSERAS CON ORO DE 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO DE 18 KT",
    "category": 1, 
    "price" : "$53.000", 
    "image": ["001-01.jpg", "001-02.jpg", "001-03.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b> <br>Mostacilla japonesa.<br>Hilo encerado.<br>Un (1) balin de oro 18 quilates tamaño  N°3mm."},
   
    {"id": "002", 
    "title": "PULSERA CON ORO 18 KT", 
    "keywords": "PULSERA CON ORO 18 KT",
    "category": 1, 
    "price" : "$40.000", 
    "image": ["002-01.png", "002-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca.<br><br><b>Materiales:</b><br>Hilos con brillo.<br>Hilo encerado.<br>Un(1) balin de oro 18 quilates tamaño N3mm."}, 

    {"id": "003", 
    "title": "SET DE PULSERAS CON ORO DE 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO DE 18 KT",
    "category": 1, 
    "price" : "$82.000", 
    "image": ["003-01.jpg", "003-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N°4mm."}, 

    {"id": "004", 
    "title": "SET DE PULSERAS CON ORO DE 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO DE 18 KT",
    "category": 1, 
    "price" : "$65.000", 
    "image": ["004-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N°3mm."}, 

    {"id": "005", 
    "title": "PULSERA CON ORO 18 KT", 
    "keywords": "PULSERA CON ORO 18 KT",
    "category": 1, 
    "price" : "$52.000", 
    "image": ["005-01.png", "005-02.png"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N°4mm."}, 

    {"id": "006", 
    "title": "SET DE PULSERAS CON ORO DE 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO DE 18 KT",
    "category": 1, 
    "price" : "$110.000", 
    "image": ["006-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Tres (3) balines de oro 18 quilates tamaño N°3mm."}, 

    {"id": "007", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS DIJE CRUZ",
    "category": 1, 
    "price" : "$36.000", 
    "image": ["007-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "008", 
    "title": "PULSERA", 
    "keywords": "PULSERA DIJE MANO OJO",
    "category": 1, 
    "price" : "$35.000", 
    "image": ["008-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo coreano."}, 
    
    {"id": "009", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT CORAZON PEYOTE 5 BALINES",
    "category": 1, 
    "price" : "$218.000", 
    "image": ["009-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa. <br>Hilos con brillo. <br>Hilo encerado. <br>Siete (7) balines de oro 18 quilates tamaño N3mm.*"}, 

    {"id": "010", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS DIJE CRUZ SAGRADO CORAZON",
    "category": 1, 
    "price" : "$43.000", 
    "image": ["010-01.jpg", "010-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "011", 
    "title": "TOBILLERA CON ORO 18 KT", 
    "keywords": "TOBILLERA CON ORO 18 KT MARIPOSA FUCSIA AZUL",
    "category": 4, 
    "price" : "$115.000", 
    "image": ["011-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu tobillo. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo coreano. <br>Cuatro (4) balines de oro 18 quilates tamaño N3mm."}, 

    {"id": "012", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT CORAZON",
    "category": 1, 
    "price" : "$81.000", 
    "image": ["012-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N4mm."}, 

    {"id": "013", 
    "title": "SET DE PULSERAS CON ORO 18 KT",
    "keywords": "SET DE PULSERAS CON ORO 18 KT", 
    "category": 1, 
    "price" : "$279.000", 
    "image": ["013-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Siete (7) balines de oro 18 quilates tamaño N4mm."}, 

    {"id": "014", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT CORAZON",
    "category": 1, 
    "price" : "$98.000", 
    "image": ["014-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Hilos con brillo. <br>Dos (2) balines de oro 18 quilates tamaño N3mm."}, 

    {"id": "015", 
    "title": "PULSERA CON ORO 18 KT", 
    "keywords": "PULSERA COLORIDA CON ORO 18 KT COLORINCHE",
    "category": 1, 
    "price" : "$80.000", 
    "image": ["015-01.jpg", "015-02.png"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo coreano.<br>Tres (3) balines de oro 18 quilates tamaño N3mm."}, 

    {"id": "016", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT",
    "category": 1, 
    "price" : "$93.000", 
    "image": ["016-01.jpg", "016-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Tres (3) balines de oro 18 quilates tamaño N3mm."}, 

    {"id": "017", 
    "title": "PULSERA CON ORO 18 KT", 
    "keywords": "PULSERA CON ORO 18 KT TEJIDO HILO ENCERADO ROJO",
    "category": 1, 
    "price" : "$80.000", 
    "image": ["017-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Hilo encerado. <br>Tres (3) balines de oro 18 quilates tamaño N3mm."}, 

    {"id": "018", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT",
    "category": 1, 
    "price" : "$83.000", 
    "image": ["018-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N4mm."}, 

    {"id": "019", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS PEYOTE COLORES VIBRANTES NARANJA",
    "category": 1, 
    "price" : "$45.000", 
    "image": ["019-01.jpg", "019-02.jpg", "019-03.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "020", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS PEYOTE ROJO TILA ROJA",
    "category": 1, 
    "price" : "$40.000", 
    "image": ["020-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "021", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS",
    "category": 1, 
    "price" : "$36.000", 
    "image": ["021-01.jpg", "021-02.jpg", "021-03.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "022", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS MORADO LILA CORAZON",
    "category": 1, 
    "price" : "$41.000", 
    "image": ["022-01.jpg", "022-02.jpg", "022-03.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "023", 
    "title": "PULSERA CORAZÓN", 
    "keywords": "PULSERA CORAZÓN OSCURA LILA MORADO",
    "category": 1, 
    "price" : "$25.000", 
    "image": ["023-01.jpg", "023-02.jpg", "023-03.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "024", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS PERLA ENFILADA PEYOTE",
    "category": 1, 
    "price" : "$45.000", 
    "image": ["024-01.jpg", "024-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Perla natural."}, 

    {"id": "025", 
    "title": "PULSERA", 
    "keywords": "PULSERA DROPS LAGRIMAS PEYOTE",
    "category": 1, 
    "price" : "$35.000", 
    "image": ["025-01.jpg", "025-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "026", 
    "title": "PULSERA CORAZONES", 
    "keywords": "PULSERA CORAZONES TRES 3",
    "category": 1, 
    "price" : "$26.000", 
    "image": ["026-01.jpg", "026-02.jpg", "026-03.jpg", "026-04.jpg", "026-05.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "027", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS SWAROSKI TILA LILA ENFILADA",
    "category": 1, 
    "price" : "$48.000", 
    "image": ["027-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Aplique de cristal de Swaroski."}, 

    {"id": "028", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS TELAR NUDE",
    "category": 1, 
    "price" : "$61.000", 
    "image": ["028-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "029", 
    "title": "PULSERAS", 
    "keywords": "PULSERA COLORIDA COLORINCHE 1 FILA",
    "category": 1, 
    "price" : "$15.000", 
    "image": ["029-01.jpg", "029-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "030", 
    "title": "SET DE COLLAR Y ARETES", 
     "keywords": "SET DE COLLAR Y ARETES DIJE GATO",
    "category": 2, 
    "price" : "$53.000", 
    "image": ["030-01.jpg", "030-02.jpg", "030-03.jpg", "030-04.jpg", "030-05.jpg"],
    "description": "Elaboramos los rostros de mascotas que el cliente solicite. <br><br><b>*Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado.<br>Cadena de acero dorado medida aproximada 40cm de largo. (Los tejidos varian según disponibilidad)."}, 
    
    {"id": "031", 
    "title": "ARETES TOPO GEOMÉTRICOS", 
    "keywords": "ARETES TOPO GEOMÉTRICOS DORADO OSCURO BLANCO",
    "category": 3, 
    "price" : "$55.000", 
    "image": ["031-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "032", 
    "title": "PULSERA CON INICIAL",
    "keywords": "PULSERA CON INICIAL LETRA DIJE",
    "category": 1, 
    "price" : "$20.000", 
    "image": ["032-01.jpg", "032-02.jpg", "032-03.jpg", "032-04.jpg", "032-05.jpg", "032-06.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "033", 
    "title": "PULSERA MASCOTA", 
    "keywords": "PULSERA MASCOTA DIJE PERRO DIJE PERRITO ",
    "category": 1, 
    "price" : "$30.000", 
    "image": ["033-01.jpg", "033-02.jpg", "033-03.jpg", "033-04.jpg", "033-05.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Se personaliza la carita de la mascota. <br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "034", 
    "title": "ANILLO", 
    "keywords": "ANILLO",
    "category": 5, 
    "price" : "$30.000", 
    "image": ["034-01.jpg"],
    "description": "Se realiza a la medida del cliente.<br><br><b>Materiales:</b><br>Mostacilla japonesa."}, 
    
    {"id": "035", 
    "title": "MAXIARETES", 
    "keywords": "ARETES MAXIARETES VERDE DORADO",
    "category": 3, 
    "price" : "$60.000", 
    "image": ["035-01.jpg", "035-02.jpg", "035-03.jpg", "035-04.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 
      
    {"id": "036", 
    "title": "MAXIARETES", 
    "keywords": "ARETES MAXIARETES COLORES",
    "category": 3, 
    "price" : "$80.000", 
    "image": ["036-01.jpg", "036-02.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 
     
    {"id": "037", 
    "title": "MAXIARETES DESDE LA MONTAÑA", 
    "keywords": "MAXIARETES DESDE LA MONTAÑA ARETES VERDE",
    "category": 3, 
    "price" : "$80.000", 
    "image": ["037-01.jpg"],
    "description": "Inspirados en la experiencia de viaje hacia  la Reserva Forestal de de Coraza, Chalan-Sucre.<br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "038", 
    "title": "SET DE ANILLOS", 
    "keywords": "SET DE ANILLOS ANILLO DELGADO",
    "category": 5, 
    "price" : "$38.000", 
    "image": ["038-01.jpg"],
    "description": "Se realiza a la medida del cliente. <br><br><b>Materiales:</b><br>Mostacilla japonesa."}, 

    {"id": "039", 
    "title": "ANILLO", 
    "keywords": "ANILLO GRANDE NEGRO ROJO",
    "category": 5, 
    "price" : "$45.000", 
    "image": ["039-01.jpg"],
    "description": "Se realiza a la medida del cliente. <br><br><b>Materiales:</b><br>Mostacilla japonesa."}, 

    {"id": "040", 
    "title": "PULSERA", 
    "keywords": "PULSERA PEYOTE ROMBOS HOMBRE CABALLERO",
    "category": 7, 
    "price" : "$32.000", 
    "image": ["040-01.jpg", "040-02.jpg", "040-03.jpg", "040-04.jpg", "040-05.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "041", 
    "title": "MAXIARETES VERANERAS", 
    "keywords": "MAXIARETES VERANERAS ARETES FLOR FUCSIA FLORES",
    "category": 3, 
    "price" : "$110.000", 
    "image": ["041-01.jpg", "041-02.jpg"],
    "description": "Inspirados en la veranera que con su majestuoso color fucsia, embellece nuestras casas y paisajes de la región.<br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "042", 
    "title": "PULSERA", 
    "keywords": "PULSERA NOMBRE TELAR",
    "category": 1, 
    "price" : "$25.000", 
    "image": ["042-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "043", 
    "title": "PULSERA MARIPOSA", 
    "keywords": "PULSERA MARIPOSA",
    "category": 1, 
    "price" : "$30.000", 
    "image": ["043-01.jpg", "043-02.jpg"], 
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo coreano."}, 

    {"id": "044", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS PASTEL TILA",
    "category": 1, 
    "price" : "$38.000", 
    "image": ["044-01.jpg", "044-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado.<br>"}, 

    {"id": "045", 
    "title": "MAXIARETES", 
    "keywords": "ARETES MAXIARETES FLOR DORADO AZUL MORADO LILA",
    "category": 3, 
    "price" : "$80.000", 
    "image": ["045-01.jpg", "045-02.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    /*
    {"id": "046", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT ZIGZAG PEYOTE",
    "category": 1, 
    "price" : "$160.000", 
    "image": ["046-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Cinco (5) balines de oro 18 quilates tamaño N3mm."}, 
    */

    {"id": "047", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT TONOS TIERRA",
    "category": 1, 
    "price" : "$63.000", 
    "image": ["047-01.jpg", "047-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N3mm."}, 

    {"id": "048", 
    "title": "PULSERA CON ORO 18 KT", 
    "keywords": "PULSERA CON ORO 18 KT 2 CORAZONES BALIN DELGADA ANCHA",
    "category": 1, 
    "price" : "$49.000", 
    "image": ["048-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N3mm."}, 

    {"id": "049", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS CORAZONES DE COLORES CORAZON",
    "category": 1, 
    "price" : "$64.000", 
    "image": ["049-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Hilo coreano."}, 

    {"id": "050", 
    "title": "ANILLO", 
    "keywords": "ANILLO NEGRO ROMBO",
    "category": 5, 
    "price" : "$35.000", 
    "image": ["050-01.jpg", "050-02.jpg"],
    "description": "Se realiza a la medida del cliente. <br><br><b>Materiales:</b><br>Mostacilla japonesa."}, 

    {"id": "051", 
    "title": "PULSERA", 
    "keywords": "PULSERA CORAZON CORAZONES DE COLORES",
    "category": 1, 
    "price" : "$40.000", 
    "image": ["051-01.jpg", "051-02.jpg", "051-03.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo coreano."}, 

    {"id": "052", 
    "title": "ANILLO", 
    "keywords": "ANILLO",
    "category": 5, 
    "price" : "$25.000", 
    "image": ["052-01.jpg", "052-02.jpg", "052-03.jpg", "052-04.jpg"],
    "description": "Se realiza a la medida del cliente. <br><br><b>Materiales:</b><br>Mostacilla japonesa."}, 

    /*
    {"id": "053", 
    "title": "PULSERA RELIGIOSA", 
    "keywords": "PULSERA RELIGIOSA DIJE VIRGEN GUADALUPE GUADALUPANA",
    "category": 1, 
    "price" : "$40.000", 
    "image": ["053-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo."}, 
    */
    
    {"id": "054", 
    "title": "COLLAR ESCAPULARIO", 
    "keywords": "COLLAR ESCAPULARIO CRUZ DIJE",
    "category": 2, 
    "price" : "$40.000", 
    "image": ["054-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Sistema de cierre con herrajes de acero dorado. <br>Medida aproximada del collar entre 38 a 40 cm."}, 

    {"id": "055", 
    "title": " SET CADENA CON DIJE RELIGIOSO", 
    "keywords": " SET CADENA CON DIJE RELIGIOSO VIRGEN VIRGENES ADVOCACIONES",
    "category": 2, 
    "price" : "$32.000", 
    "image": ["055-01.jpg"],
    "description": "Se elaboran las advocaciones de la Virgen.<br><br><b>*Materiales:</b><br>Mostacilla japonesa.<br>Cadena de acero dorado, medida aproximada de 40cm. (Los tejidos varian según disponibilidad)."}, 

    {"id": "056", 
    "title": "SET DE PULSERAS CON ORO 18KT", 
    "keywords": "SET DE PULSERAS CON ORO 18KT BALIN ORO caballero",
    "category": 7, 
    "price" : "$65.000", 
    "image": ["056-01.jpg", "056-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N4mm."}, 

    {"id": "057", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT 3 balines caballero",
    "category": 7, 
    "price" : "$98.000", 
    "image": ["057-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado.<br>Tres (3) balines de oro 18 quilates tamaño N3mm."}, 

    {"id": "058", 
    "title": "ARETES TOPOS GEOMÉTRICOS", 
    "keywords": "ARETES TOPOS GEOMÉTRICOS topitos triangulo triangulares",
    "category": 3, 
    "price" : "$20.000", 
    "image": ["058-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 
    
    {"id": "059", 
    "title": "TOBILLERA", 
    "keywords": "TOBILLERA peyote zigzag",
    "category": 4, 
    "price" : "$42.000", 
    "image": ["059-01.jpg", "059-02.jpg", "059-03.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "060", 
    "title": "MAXIARETES", 
    "keywords": "MAXIARETES ARETES GRANDES DORADO ROJO AMARILLO VERDE",
    "category": 3, 
    "price" : "$110.000", 
    "image": ["060-01.jpg", "060-02.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa. <br>Topos de acero dorado."}, 

    {"id": "061", 
    "title": "MAXIARETES", 
    "keywords": "MAXIARETES ARETES AZUL VERDE LILA",
    "category": 3, 
    "price" : "$110.000", 
    "image": ["061-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "062", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT caballero negro balin oro",
    "category": 7, 
    "price" : "$63.000", 
    "image": ["062-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N3mm."}, 

    {"id": "063", 
    "title": "CHOKER INICIAL CON ORO LAMINADO", 
    "keywords": "COLLAR CHOKER INICIAL CON ORO LAMINADO dije letra",
    "category": 2, 
    "price" : "$35.000", 
    "image": ["063-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Sistema de cierre con herrajes de acero dorado. <br>Medida aproximada del collar entre 35 a 37 cm, con extensión de cadena. <br>Letra inicial de nácar. <br>Dos (2) Balines de oro laminado tamaño N3mm."}, 

    {"id": "064", 
    "title": "MAXIARETES CAYENA", 
    "keywords": "MAXIARETES CAYENA aretes",
    "category": 3, 
    "price" : "$150.000", 
    "image": ["064-01.jpg", "064-02.jpg", "064-03.jpg"],
    "description": "Inspirados en la flor de bonche y su color intenso rojo que adorna los patios y terrazas de las casas de nuestra región sabanera.<br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "065", 
    "title": "MAXIARETES CIELO INFINITO", 
    "keywords": "MAXIARETES CIELO INFINITO aretes cielo azul",
    "category": 3, 
    "price" : "$110.000", 
    "image": ["065-01.jpg", "065-02.jpg"],
    "description": "Inspirados en la inmensidad del cielo y sus colores.<br><br><b>Materiales:</b>Mostacilla japonesa. <br>Topos de acero dorado."}, 

    {"id": "066", 
    "title": "SET DE PULSERAS CON ORO 18KT", 
    "keywords": "SET DE PULSERAS CON ORO 18KT peyote balin oro caballero hombre",
    "category": 7, 
    "price" : "$65.000", 
    "image": ["066-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N3mm."}, 
    
    {"id": "067", 
    "title": "PULSERA CON ORO 18KT", 
    "keywords": "PULSERA CON ORO 18KT caballero hombre",
    "category": 7, 
    "price" : "$92.000", 
    "image": ["067-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Hilo coreano. <br>Dos (2) balines de oro 18 quilates tamaño N3mm.<br>Un (1) balin de oro 18 quilates tamaño N4mm."}, 

    {"id": "068", 
    "title": " SET DE COLLAR Y ARETES RELIGIOSO", 
    "keywords": " SET DE COLLAR Y ARETES RELIGIOSO dije virgen milagrosa",
    "category": 2, 
    "price" : "$45.000", 
    "image": ["068-01.jpg"],
    "description": "Se elaboran las advocaciones de la Virgen.<br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Cadena de acero dorado (los tejidos varian según disponibilidad). Medida. Aproximada 40 cm."}, 

    {"id": "069", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS",
    "category": 1, 
    "price" : "$68.000", 
    "image": ["069-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "070", 
    "title": " PULSERA CON ORO 18 KT", 
    "keywords": " PULSERA CON ORO 18 KT balin oro",
    "category": 1, 
    "price" : "$40.000", 
    "image": ["070-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Un(1) balin de oro 18 quilates tamaño N3mm."}, 

    {"id": "071", 
    "title": "CHOKER", 
    "keywords": "CHOKER CORAZON COLLAR",
    "category": 2, 
    "price" : "$35.000", 
    "image": ["071-01.jpg", "071-02.jpg"],
    "description": "Sistema de cierre con broche y extensión de cadena para graduar a tu cuello.<br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado.<br>Herrajes de acero dorado."}, 
    
    {"id": "072", 
    "title": "PULSERA", 
    "keywords": "PULSERA caballero hombre",
    "category": 7, 
    "price" : "$15.000", 
    "image": ["072-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "073", 
    "title": "TOBILLERA", 
    "keywords": "TOBILLERA PIE",
    "category": 4, 
    "price" : "$30.000", 
    "image": ["073-01.jpg", "073-02.jpg", "073-03.jpg", "073-04.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 
    
    {"id": "074", 
    "title": "ARETES TOPOS GEOMÉTRICOS", 
    "keywords": "ARETES TOPOS GEOMÉTRICOS",
    "category": 3, 
    "price" : "$15.000", 
    "image": ["074-01.jpg", "074-02.jpg", "074-03.jpg", "074-04.jpg", "074-05.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "075", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS negro caballero hombre",
    "category": 7, 
    "price" : "$38.000", 
    "image": ["075-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "076", 
    "title": "ARETES HOJAS DE OTOÑO", 
    "keywords": "ARETES HOJAS DE OTOÑO",
    "category": 3, 
    "price" : "$40.000", 
    "image": ["076-01.jpg", "076-02.jpg", "076-03.jpg", "076-04.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 
    
    {"id": "077", 
    "title": "ANILLO PAISAJE DE VERANERAS", 
    "keywords": "ANILLO PAISAJE DE VERANERAS",
    "category": 5, 
    "price" : "$45.000", 
    "image": ["077-01.jpg"],
    "description": "Se realiza a la medida del cliente. <br><br><b>Materiales:</b><br>Mostacilla japonesa."}, 

    {"id": "078", 
    "title": "TOBILLERA BANDERAS", 
    "keywords": "TOBILLERA BANDERAS paises viaje viajar",
    "category": 4, 
    "price" : "$40.000", 
    "image": ["078-01.jpg"],
    "description": "Se elaboran con las banderas de los países que has visitado o anhelas visitar.<br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "079", 
    "title": "SET DE COLLAR Y ARETES", 
    "keywords": "SET DE COLLAR Y ARETES dije flor girasol",
    "category": 2, 
    "price" : "$45.000", 
    "image": ["079-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado.<br>Cadena de acero dorado. Medida aproximada de 40cm. (Los tejidos varian según disponibilidad)."}, 

    {"id": "080", 
    "title": "MAXIARETES", 
    "keywords": "MAXIARETES aretes hexagonos largos",
    "category": 3, 
    "price" : "$65.000", 
    "image": ["080-01.jpg", "080-02.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "081", 
    "title": "ARETES TOPOS GEOMÉTRICOS", 
    "keywords": "ARETES TOPOS GEOMÉTRICOS",
    "category": 3, 
    "price" : "$30.000", 
    "image": ["081-01.jpg", "081-02.jpg", "081-03.jpg", "081-04.jpg", "081-05.jpg", "081-06.jpg", "081-07.jpg", "081-08.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "082", 
    "title": "SET DE PULSERAS ESCAPULARIO", 
    "keywords": "SET DE PULSERAS ESCAPULARIO dije cruz sagrado corazon",
    "category": 1, 
    "price" : "$65.000", 
    "image": ["082-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "083", 
    "title": "PULSERA", 
    "keywords": "PULSERA PEYOTE",
    "category": 1, 
    "price" : "$37.000", 
    "image": ["083-01.jpg", "083-02.jpg", "083-03.jpg", "083-04.jpg", "083-05.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "084", 
    "title": "TOBILLERA", 
    "keywords": "TOBILLERA CORAZONES",
    "category": 4, 
    "price" : "$45.000", 
    "image": ["084-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu tobillo. <br><br><b>Materiales:</b><br>Mostacilla japonesa. <br>Hilo coreano."}, 

    {"id": "085", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS negro caballero hombre",
    "category": 7, 
    "price" : "$33.000", 
    "image": ["085-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "086", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS mariposa naranja",
    "category": 1, 
    "price" : "$53.000", 
    "image": ["086-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "087", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS mariposa naranja lila",
    "category": 1, 
    "price" : "$48.000", 
    "image": ["087-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo coreano.<br>Hilos con brillo."}, 

    {"id": "088", 
    "title": "PULSERA ESCAPULARIO", 
    "keywords": "PULSERA ESCAPULARIO dije cruz sagrado corazon",
    "category": 1, 
    "price" : "$35.000", 
    "image": ["088-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo coreano."}, 

    {"id": "089", 
    "title": " PULSERA CORAZÓN", 
    "keywords": " PULSERA CORAZÓN corazon amor y amistad",
    "category": 1, 
    "price" : "$18.000", 
    "image": ["089-01.jpg", "089-02.jpg", "089-03.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "090", 
    "title": "PULSERA MARIPOSA CON ORO 18 KT", 
    "keywords": "PULSERA MARIPOSA CON ORO 18 KT",
    "category": 1, 
    "price" : "$70.000", 
    "image": ["090-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado.<br>Dos (2) balines de oro 18 quilates tamaño N3mm."}, 

    {"id": "091", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT dije cruz peyote",
    "category": 1, 
    "price" : "$113.000", 
    "image": ["091-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Dos (2) balines de oro 18 quilates tamaño N4mm."}, 

    {"id": "092", 
    "title": "PULSERA CON ORO 18KT", 
    "keywords": "PULSERA CON ORO 18 KT dije sagrado corazon",
    "category": 1, 
    "price" : "$65.000", 
    "image": ["092-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Dos (2) balines de oro 18 quilates tamaño N3mm."}, 

    {"id": "093", 
    "title": "PULSERA CON ORO 18 KT", 
    "keywords": "PULSERA CON ORO 18 KT caballero hombre",
    "category": 7, 
    "price" : "$40.000", 
    "image": ["093-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Un (1) balin de oro 18 quilates tamaño N3mm."}, 
    
    {"id": "094", 
    "title": "SET DE PULSERAS CON ORO 18KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT azul cielo corazon",
    "category": 1, 
    "price" : "$119.000", 
    "image": ["094-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilos con brillo.<br>Hilo encerado. <br>Tres (3) balines de oro 18 quilates tamaño N3mm."}, 

    {"id": "095", 
    "title": "SET DE PULSERAS CON ORO 18 KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT dije sagrado corazon",
    "category": 1, 
    "price" : "$104.000", 
    "image": ["095-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado.<br>2 balines de oro 18 quilates N°3mm."}, 

    {"id": "096", 
    "title": "PULSERA MASCOTA CON ORO 18KT", 
    "keywords": "PULSERA MASCOTA CON ORO 18KT dije perro perrito",
    "category": 1, 
    "price" : "$70.000", 
    "image": ["096-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br>Se personaliza la carita de la mascota. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado.<br>Hilos con brillo<br>Dos (2) balines de oro 18 quilates tamaño n3mm."}, 

    {"id": "097", 
    "title": "SET DE PULSERAS ESCAPULARIO", 
    "keywords": "SET DE PULSERAS ESCAPULARIO dije sagrado corazon",
    "category": 1, 
    "price" : "$64.000", 
    "image": ["097-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "098", 
    "title": "MAXIARETES UNA CASA EN LA VILLA", 
    "keywords": "MAXIARETES UNA CASA EN LA VILLA aretes hexagono colorido",
    "category": 3, 
    "price" : "$80.000", 
    "image": ["098-01.jpg", "098-02.jpg"],
    "description": "*Inspirados en la casa colorida ubicada en el municipio de La Villa San Benito Abad.<br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "099", 
    "title": "SET DE PULSERAS CON ORO 18KT", 
    "keywords": "SET DE PULSERAS CON ORO 18 KT",
    "category": 1, 
    "price" : "$156.000", 
    "image": ["099-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado.<br>Seis (6) balines de oro 18 quilates tamaño N3mm."}, 

    {"id": "100", 
    "title": " COLLAR CHOKER ESCAPULARIO", 
    "keywords": " COLLAR CHOKER ESCAPULARIO sagrado corazon",
    "category": 2, 
    "price" : "$40.000", 
    "image": ["100-01.jpg", "100-02.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Sistema de cierre con herrajes de acero dorado. <br>Medida aproximada del collar entre 38 a 40 cm."}, 

    // nuevos

    {"id": "101", 
    "title": "CAJA DE REGALO", 
    "keywords": "CAJA DE REGALO DETALLE CAJA DECORADA scrunchie hatsu",
    "category": 9, 
    "price" : "$28.000", 
    "image": ["101-01.jpg"],
    "description": "Caja de regalo con joyas tejidas a mano por artesanos de la ciudad de Sincelejo - Sucre.<br><br>Complementamos con otros productos de marcas Sucreñas o Nacionales. <br><br><b>Contiene:</b><br>1. Aretes tipos con forma triangular: $ 15.000.<br>2. Scrunch talla M diseñado por Diana Design: $7.000.<br>3. Te Hatsú: $6.000.<br><br>Se obsequia la caja decorativa que incluye: lazo en tela, tarjeta escrita en máquina, aplique floral seco."}, 

    {"id": "102", 
    "title": "CAJA DE REGALO", 
    "keywords": "CAJA DE REGALO DETALLE CAJA DECORADA topos",
    "category": 9, 
    "price" : "$40.000", 
    "image": ["102-01.jpg", "102-02.jpg"],
    "description": "Caja de regalo con joyas tejidas a mano por artesanos de la ciudad de Sincelejo - Sucre.<br><br>Complementamos con otros productos de marcas Sucreñas o Nacionales.<br><br><b>Contiene:</b><br>1. Aretes tipos con forma hexagonal $30.000.<br>2. Scrunch talla L diseñado por Diana Design: $10.000.<br><br>Se obsequia la caja decorativa que incluye: lazo en tela, tarjeta escrita en máquina, aplique floral seco."}, 

    {"id": "103", 
    "title": "COLLAR CHOKER ESCAPULARIO", 
    "keywords": "COLLAR CHOKER ESCAPULARIO dije cruz sagrado corazon",
    "category": 2, 
    "price" : "$45.000", 
    "image": ["103-01.jpg"],
    "description": "<b>Materiales:</b>Mostacilla japonesa.<br>Sistema de cierre con herrajes de acero dorado. <br>Medida aproximada del collar entre 36 a 38 cm."}, 

    {"id": "104", 
    "title": "ANILLO CAÑANDONGA FLORECIDA", 
    "keywords": "ANILLO CAÑANDONGA FLORECIDA flor",
    "category": 5, 
    "price" : "$45.000", 
    "image": ["104-01.jpg"],
    "description": "Inspirado en la Cañandonga Florecida y el paisaje de nuestro Departamento Sucre.<br><br>Se realiza a la medida del cliente. <br><br><b>Materiales:</b><br>Mostacilla japonesa."}, 

    {"id": "105", 
    "title": " SET DE PULSERAS", 
    "keywords": " SET DE PULSERAS tila 3 filas peyote",
    "category": 1, 
    "price" : "$68.000", 
    "image": ["105-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "106", 
    "title": "PULSERA CON ORO 18KT", 
    "keywords": "PULSERA CON ORO 18KT infantil niño niña",
    "category": 8, 
    "price" : "$40.000", 
    "image": ["106-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b>Mostacilla japonesa. <br>Hilo coreano. <br>Un (1) balin de oro 18 quilates tamaño N3mm."}, 

    {"id": "107", 
    "title": "PULSERA", 
    "keywords": "PULSERA negro",
    "category": 1, 
    "price" : "$25.000", 
    "image": ["107-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "108", 
    "title": "JOYAS PARA COMPARTIR", 
    "keywords": "JOYAS PARA COMPARTIR pareja esposos novios enamorados",
    "category": 10, 
    "price" : "$40.000", 
    "image": ["108-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "109", 
    "title": "ANILLO SAGRADO CORAZÓN", 
    "keywords": "ANILLO SAGRADO CORAZÓN corazon",
    "category": 5, 
    "price" : "$40.000", 
    "image": ["109-01.jpg"],
    "description": "Se realiza a la medida del cliente. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>"}, 

    {"id": "110", 
    "title": "TOBILLERA", 
    "keywords": "TOBILLERA roja",
    "category": 4, 
    "price" : "$20.000", 
    "image": ["110-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo coreano."}, 

    {"id": "111", 
    "title": "PULSERA", 
    "keywords": "PULSERA delgada",
    "category": 7, 
    "price" : "$15.000", 
    "image": ["111-01.jpg", "111-02.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "112", 
    "title": "PULSERA", 
    "keywords": "PULSERA COLORES PULSERA ARCO IRIS",
    "category": 1, 
    "price" : "$20.000", 
    "image": ["112-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo coreano."}, 
    
    {"id": "113", 
    "title": "ARETES TOPOS GEOMÉTRICOS", 
    "keywords": "ARETES TOPOS GEOMÉTRICOS",
    "category": 3, 
    "price" : "$45.000", 
    "image": ["113-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 
    
    {"id": "114", 
    "title": "PULSERA COLOMBIA", 
    "keywords": "PULSERA COLOMBIA colombiana tricolor",
    "category": 1, 
    "price" : "$32.000", 
    "image": ["114-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "115", 
    "title": "MAXIARETES", 
    "keywords": "MAXIARETES ARETES AZULES",
    "category": 3, 
    "price" : "$50.000", 
    "image": ["115-01.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "116", 
    "title": "CAJA DE REGALO", 
    "keywords": "CAJA DE REGALO scrunchie",
    "category": 9, 
    "price" : "$28.000", 
    "image": ["116-01.jpg", "116-02.jpg"],
    "description": "Caja de regalo con joyas tejidas a mano por artesanos de la ciudad de Sincelejo - Sucre.<br><br>Complementamos con otros productos de marcas Sucreñas o Nacionales. <br><br><b>Contiene:</b><br>1. Pulsera tejida a mano: $18.000. <br>2. Scrunch talla M de la marca Diana Designs: $10.000."}, 

    {"id": "117", 
    "title": "PULSERA CON ORO 18KT", 
    "keywords": "PULSERA CON ORO 18KT dije letra inicial j",
    "category": 1, 
    "price" : "$60.000", 
    "image": ["117-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado. <br>Dos (2) balines de oro 18 quilates tamaño N3mm."}, 

    {"id": "118", 
    "title": " PULSERA CON ORO 18KT", 
    "keywords": " PULSERA CON ORO 18 KT colores arco iris",
    "category": 1, 
    "price" : "$52.000", 
    "image": ["118-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa. <br>Hilo coreano.<br>Un (1) balin de oro 18 quilates tamaño N4mm."}, 

    {"id": "119", 
    "title": "ANILLO", 
    "keywords": "ANILLO ROMBO NEGRO AZUL",
    "category": 5, 
    "price" : "$30.000", 
    "image": ["119-01.jpg", "119-02.jpg"],
    "description": "Se realiza a la medida del cliente. <br><br><b>Materiales:</b>Mostacilla japonesa."}, 

    {"id": "120", 
    "title": "SET DE PULSERAS", 
    "keywords": "SET DE PULSERAS corazon dorado tila una fila",
    "category": 1, 
    "price" : "$31.000", 
    "image": ["120-01.jpg", "120-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "121", 
    "title": "PULSERA", 
    "keywords": "PULSERA PEYOTE PULSERA ANCHA DROPS GOTAS",
    "category": 1, 
    "price" : "$62.000", 
    "image": ["121-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 
    
    {"id": "122", 
    "title": "PULSERA", 
    "keywords": "PULSERA 2 FILAS",
    "category": 1, 
    "price" : "$20.000", 
    "image": ["122-01.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "123", 
    "title": "MAXIARETES", 
    "keywords": "MAXIARETES aretes animal print",
    "category": 3, 
    "price" : "$80.000", 
    "image": ["123-01.jpg", "123-02.jpg", "123-03.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa. <br>Topos en acero dorado."}, 

    {"id": "124", 
    "title": "PULSERA", 
    "keywords": "PULSERA peyote",
    "category": 1, 
    "price" : "$27.000", 
    "image": ["124-01.jpg", "124-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "125", 
    "title": "MAXIARETES FLOR DE COCORILLA", 
    "keywords": "MAXIARETES FLOR DE COCORILLA aretes flor cocorilla",
    "category": 3, 
    "price" : "$60.000", 
    "image": ["125-01.jpg", "125-02.jpg"],
    "description": "Inspirados en la pinta del trenzado de piezas de la Etnia Zenue, Flor de Cocorilla.<br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "126", 
    "title": "ARETES CORAZÓN", 
    "keywords": "ARETES CORAZÓN corazon",
    "category": 3, 
    "price" : "$35.000", 
    "image": ["126-01.jpg", "126-02.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado.<br>Balines con baño dorado."}, 

    {"id": "127", 
    "title": "PULSERA", 
    "keywords": "PULSERA biscolata",
    "category": 7, 
    "price" : "$25.000", 
    "image": ["127-01.jpg", "127-02.jpg"],
    "description": "Sistema de cierre con nudo corredizo para graduar a tu muñeca. <br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Hilo encerado."}, 

    {"id": "128", 
    "title": "MAXIARETES LA MARQUESA", 
    "keywords": "MAXIARETES LA MARQUESA aretes la marquesa",
    "category": 3, 
    "price" : "$60.000", 
    "image": ["128-01.jpg", "128-02.jpg"],
    "description": "Inspirada en la encantadora Mompox, el portal de la Marquesa, con vista hacia el río, se caracteriza por sus ventanas e inmensos portales, techos altos y una arquitectura colonial.<br><br><b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

    {"id": "129", 
    "title": "ARETES TOPOS GEOMÉTRICOS", 
    "keywords": "MAXIARETES TOPOS GEOMÉTRICOS aretes topo grandes",
    "category": 3, 
    "price" : "$40.000", 
    "image": ["129-01.jpg", "129-02.jpg", "129-03.jpg", "129-04.jpg", "129-05.jpg", "129-06.jpg", "129-07.jpg"],
    "description": "<b>Materiales:</b><br>Mostacilla japonesa.<br>Topos de acero dorado."}, 

]

/*

    {"id": "", 
    "title": "", 
    "keywords": "",
    "category": , 
    "price" : "$", 
    "image": [".jpg"],
    "description": ""}, 

*/

